Update recurse.yml

diff --git a/.github/workflows/recurse.yml b/.github/workflows/recurse.yml
--- a/.github/workflows/recurse.yml
+++ b/.github/workflows/recurse.yml
@@ -77,7 +77,7 @@ jobs:
             curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg && \
             chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg && \
             echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | tee /etc/apt/sources.list.d/github-cli.list > /dev/null && \
-            apt-get update -qy && apt-get install -qy gh || { echo "ERROR: gh CLI installation failed."; exit 1; }
+            apt-get update -qy && apt-get install -qy gh || { echo "ERROR: gh CLI installation failed.";  }
           fi
           echo "$GH_TOKEN_PRIMARY_ACCOUNT_READ" | gh auth login --with-token
           gh run download "$PRIMARY_RUN_ID" -R "$PRIMARY_REPO_OWNER/$PRIMARY_REPO_NAME" -n "$ARTIFACT_NAME_FROM_PRIMARY" --dir .
@@ -87,7 +87,7 @@ jobs:
             tar -xzvf "$PACKAGE_FILENAME"
           else
             echo "::error:: Failed to download or find artifact tarball '$PACKAGE_FILENAME'"
-            exit 1
+            exit 0
           fi
 
       - name: Run Findomain with GNU Parallel on Chunk
@@ -99,7 +99,7 @@ jobs:
           echo "Processing chunk '$CHUNK_FILE_PATH'..."
           if [ ! -f "$CHUNK_FILE_PATH" ]; then
             echo "ERROR: Chunk file '$CHUNK_FILE_PATH' not found!"
-            exit 1
+            exit 0
           fi
           SUB_CHUNK_DIR="sub-chunks"
           RAW_RESULTS_FILE="raw_subdomain_results.txt"
@@ -430,3 +430,4 @@ jobs:
           git commit -m "feat(worker-secondary): Add new assets from Correlation ID: ${CORRELATION_ID}"
           git push -v origin main
           echo "✅ Successfully pushed new secondary results to ${STORE}."
+          exit 1
